[package]
name = "nost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
dotenv = "0.15"

[dev-dependencies]
tempfile = "3.6"
