name: Nost Unit Tests
run-name: Run Nost Unit Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start CI
        run: |
          echo "Starting CI..."
          echo "Running tests..."
          # Add your test command here, e.g., pytest or npm test
          # For example:
          # pytest tests/
          # or
          # npm test
